source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'MakeNoise' do

    # 界面
    pod 'SnapKit', '~> 4.0.0'                                       # 布局
    pod 'ChameleonFramework/Swift',
        :git => 'https://github.com/ViccAlexander/Chameleon.git'    # 颜色扩展
    pod 'HGRippleRadarView'                                         # 波浪动画

    # 音频处理
    pod 'AudioKit', '~> 4.0'
    pod 'AudioKit/UI'

    pod 'Upsurge', '~> 0.10.2'
    pod 'OpenCV', '~> 3.3.1'

end
